import { Item } from "./types";

export const initialItems: Item[] = [
  { id: "1", name: "T-Shirt", category: "clothing", isPacked: false },
  { id: "2", name: "Laptop", category: "electronics", isPacked: false },
  { id: "3", name: "Toothbrush", category: "toiletries", isPacked: false },
  { id: "4", name: "Passport", category: "documents", isPacked: false },
  { id: "5", name: "Watch", category: "accessories", isPacked: false },
  { id: "6", name: "Mobile Phone", category: "electronics", isPacked: false },
  { id: "7", name: "Charger", category: "electronics", isPacked: false },
  { id: "8", name: "Headphones", category: "electronics", isPacked: false },
  { id: "9", name: "Wallet", category: "accessories", isPacked: false },
  { id: "10", name: "Jeans", category: "clothing", isPacked: false },
  { id: "11", name: "Towel", category: "toiletries", isPacked: false },
  { id: "12", name: "Soap", category: "toiletries", isPacked: false },
  { id: "13", name: "Shampoo", category: "toiletries", isPacked: false },
  { id: "14", name: "Perfume", category: "toiletries", isPacked: false },
  { id: "15", name: "Sunglasses", category: "accessories", isPacked: false },
  { id: "16", name: "Notebook", category: "stationary", isPacked: false },
  { id: "17", name: "Pen", category: "stationary", isPacked: false },
  { id: "18", name: "Earbuds", category: "toiletries", isPacked: false },
  { id: "19", name: "Power Bank", category: "electronics", isPacked: false },
  { id: "20", name: "Handkerchief", category: "accessories", isPacked: false },
  { id: "21", name: "Slippers", category: "clothing", isPacked: false },
  { id: "22", name: "Shoes", category: "clothing", isPacked: false },
  { id: "23", name: "Water Bottle", category: "accessories", isPacked: false },
  { id: "24", name: "Snacks", category: "food", isPacked: false },
  { id: "25", name: "Tea Bags", category: "food", isPacked: false },
  { id: "26", name: "Hair Comb", category: "toiletries", isPacked: false },
  { id: "27", name: "Medicines", category: "health", isPacked: false },
  { id: "28", name: "Face Wash", category: "toiletries", isPacked: false },
  { id: "29", name: "Mask", category: "health", isPacked: false },
  { id: "30", name: "Umbrella", category: "accessories", isPacked: false },
  { id: "31", name: "Cotton Swabs", category: "toiletries", isPacked: false },
  { id: "32", name: "Chappals", category: "clothing", isPacked: false },
  { id: "33", name: "Smartwatch", category: "electronics", isPacked: false },
  { id: "34", name: "ID Card", category: "documents", isPacked: false },
  { id: "35", name: "Mobile Stand", category: "electronics", isPacked: false },
  { id: "36", name: "Data Cable", category: "electronics", isPacked: false },
  { id: "37", name: "Belt", category: "accessories", isPacked: false },
  { id: "38", name: "Hand Sanitizer", category: "health", isPacked: false },
  { id: "39", name: "Dairy", category: "stationary", isPacked: false },
  { id: "40", name: "Keychain", category: "accessories", isPacked: false },
  { id: "41", name: "Notebook", category: "stationary", isPacked: false },
  { id: "42", name: "Sticky Notes", category: "stationary", isPacked: false },
  {
    id: "43",
    name: "Mechanical Keyboard",
    category: "electronics",
    isPacked: false,
  },
  {
    id: "44",
    name: "Wireless Mouse",
    category: "electronics",
    isPacked: false,
  },
  { id: "45", name: "HDMI Cable", category: "electronics", isPacked: false },
  {
    id: "46",
    name: "Portable Monitor",
    category: "electronics",
    isPacked: false,
  },
  {
    id: "47",
    name: "USB Flash Drive",
    category: "electronics",
    isPacked: false,
  },
  {
    id: "48",
    name: "External Hard Drive",
    category: "electronics",
    isPacked: false,
  },
  { id: "49", name: "LAN Cable", category: "electronics", isPacked: false },
  {
    id: "50",
    name: "Laptop Cooling Pad",
    category: "electronics",
    isPacked: false,
  },
  { id: "51", name: "Coding Books", category: "books", isPacked: false },
  { id: "52", name: "Reference Guides", category: "books", isPacked: false },
  {
    id: "53",
    name: "Desk Organizer",
    category: "accessories",
    isPacked: false,
  },
  { id: "54", name: "Desk Lamp", category: "accessories", isPacked: false },
  { id: "55", name: "Blue Light Glasses", category: "health", isPacked: false },
  {
    id: "56",
    name: "Extension Board",
    category: "electronics",
    isPacked: false,
  },
  { id: "57", name: "Laptop Stand", category: "accessories", isPacked: false },
  {
    id: "58",
    name: "Notebook Divider",
    category: "stationary",
    isPacked: false,
  },
  { id: "59", name: "Calculator", category: "electronics", isPacked: false },
  {
    id: "60",
    name: "Posters/Wall Art",
    category: "accessories",
    isPacked: false,
  },
  {
    id: "61",
    name: "Whiteboard Markers",
    category: "stationary",
    isPacked: false,
  },
  { id: "62", name: "Whiteboard", category: "stationary", isPacked: false },
] as const;
